#reids��IP��ַ
#spring.redis.host=127.0.0.1
#redis�˿ں�
#spring.redis.port=6379

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: user-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.31.203:1521:orcl203
    username: c##xsz
    password: xsz
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.kuang.pojo
  mapper-locations: classpath:mapper/*.xml